[colors.bright]
black = "#414868"
blue = "#7AA2F7"
cyan = "#7DCFFF"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#C0CAF5"
yellow = "#E0AF68"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#414868"
blue = "#7AA2F7"
cyan = "#7DCFFF"
green = "#9ECE6A"
magenta = "#BB9AF7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#E0AF68"

[colors.primary]
background = "#1A1B26"
dim_foreground = "#a5abb6"
foreground = "#C0CAF5"

# [colors.search.footer_bar]
# background = "#434c5e"
# foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font.normal]
family = "CaskaydiaCove Nerd Font"

[env]
term = "xterm-256color"
